apiVersion: v1
kind: Service
metadata:
    name: pocketgym-api-service
    labels:
        app: pocketgym
spec:
    type: LoadBalancer
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
    selector:
        app: pocketgym
    
